### ISSUE TITLE
Interface no longer working with the release of Chrome v67

### ISSUE THREAD

**Issue by murphyben** [shripalsoni04/nativescript-webview-interface-demo#7]
Looks like the interface is no longer working once I update to Chrome version 67 on Android.  Version 66 and below work fine.  To recreate, load a page via WebViewInterface and click on any link the page.  The app will crash with the following error:

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: Java Error!
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.android.webkit.WebViewClient_frnal_ts_helpers_l58_c38__WebViewClientImpl.shouldOverrideUrlLoading(WebViewClient_frnal_ts_helpers_l58_c38__WebViewClientImpl.java:20)
	at yk.b(PG:89)
	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Package.getName()' on a null object reference
	at com.tns.Runtime.getTypeMetadata(Runtime.java:682)
	at com.tns.Runtime.getTypeMetadata(Runtime.java:660)
	... 17 more

**Comment by murphyben** [comment]
Actually this appears to be a NativeScript webview error.

**Comment by murphyben** [comment]
Created the following Topic on the NativeScript site for anyone running into this: https://discourse.nativescript.org/t/webview-causes-app-crash-on-android-with-chrome-67-release/6202
